### ISSUE TITLE
[Proposition] Display option 'None'

### ISSUE THREAD

**Issue by AuracleTech** [Steditor/vsce-line-endings#3]
![image](https://user-images.githubusercontent.com/40531871/151849094-7c7eaa7d-5fa1-4774-8b94-d694c1c997e2.png)
Could be nice if I could deactivate it on some files, currently I have to press disable the whole extension when not in use.

Would make workflow quicker and easier

**Comment by Steditor** [comment]
Thank you for the suggestion!
The setting in your screenshot is a core setting of Visual Studio Code and is not provided by this extension. As there has to be a line ending, "none" would not work there.

Currently, whether this extension does or does not render line ending visuals is controlled by the "renderControlCharacters" setting of Visual Studio Code. You can change that setting with the "Toggle Control Characters" command. (See also https://github.com/microsoft/vscode/issues/16003 and https://github.com/microsoft/vscode/issues/12760#issuecomment-249989419)
Does this cover your workflow, or is there a need for an additional setting that allows to deactivate rendering line endings whilst still rendering other control characters?

**Comment by AuracleTech** [comment]
Oh, I thought this was part of the extension, my bad, I'd need a quick setting option so editing settings won't cut it.
I will open a ticket on vscode git, thank you for the information provided 😁 !
