### ISSUE TITLE
Is this extension can correctly render mixed line endings?

### ISSUE THREAD

**Issue by Mingun** [Steditor/vsce-line-endings#5]
Today I got a merge conflict in my git working copy that was related to different line endings. It seems that part of lines ended with CR+LF and part with LF and the difference in some lines created a merge conflict. But when I tried this extension it showed me that all lines ended with the same sequence, which is configured in VSCode. I'm doubt that this was true, because then why git (GitKraken actually) shows me the difference?

So the question: did you rended _actual_ line endings or just the _configured_ one?

**Comment by Steditor** [comment]
See #1 and https://github.com/microsoft/vscode/issues/127: VSC currently normalizes line endings, so this extension does not really do anything useful at the moment. It does show the _actual_ line endings in the editor, but those are post-normalization.

Maybe you can try out #4 as a workaround.
